
services:
  # 1. Base de Dados (Persistência para a Evolution API)
  postgres-reservatorio:
    image: postgres:16-alpine
    container_name: postgres-reservatorio
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin_monitor}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${EVOLUTION_DB_NAME:-evolution_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rede-monitoramento-hidrico

  # 2. Redis (Cache de Performance)
  redis-reservatorio:
    image: redis:7-alpine
    container_name: redis-reservatorio
    restart: unless-stopped
    networks:
      - rede-monitoramento-hidrico

  # 3. Evolution API v2.3.7 (Interface WhatsApp)
  evolution-reservatorio:
    image: evoapicloud/evolution-api:v2.3.7
    container_name: evolution-reservatorio
    restart: unless-stopped
    ports:
      - "9095:8080"
    environment:
      - SERVER_URL=http://evolution-reservatorio:8080
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=${EVOLUTION_API_KEY}
      
      # Conexão com o Banco (Lógica de Persistência v2)
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://${POSTGRES_USER:-admin_monitor}:${POSTGRES_PASSWORD}@postgres-reservatorio:5432/${EVOLUTION_DB_NAME:-evolution_db}?schema=public
      - DATABASE_CONNECTION_CLIENT_NAME=monitor_hidrico_v2
      
      # Cache Redis para performance em tempo real
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis-reservatorio:6379/0
      - CACHE_LOCAL_ENABLED=false
      
      - CONFIG_SESSION_PHONE_WATCH=true
      - QRCODE_LIMIT=30
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - rede-monitoramento-hidrico
    depends_on:
      postgres-reservatorio:
        condition: service_started
      redis-reservatorio:
        condition: service_started

  # 4. Bot de Monitoramento (Seu código em C distribuído)
  bot-monitor:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: bot-monitor-hidrico
    restart: unless-stopped
    environment:
      # URL da instância do Interscity disponível na UFMA
      - MIDDLEWARE_URL=http://ENDERECO_INTERSCITY_UFMA/resources/RES-SLZ-001/data/last
      
      # Endereço interno da API para comunicação direta no Docker
      - EVOLUTION_URL=http://evolution-reservatorio:8080
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - INSTANCE_NAME=${INSTANCE_NAME:-reservatorio-slz}
      
      # Regras de Negócio (TAP/Planejamento) (eu posso mudar, caso queiram. Sei que foge do tap mas eu quero refinar com base no teste)
      - NIVEL_CRITICO=15 
      - GESTOR_NUM=55989XXXXXXXX # Número que receberá os alertas
    networks:
      - rede-monitoramento-hidrico
    depends_on:
      evolution-reservatorio:
        condition: service_healthy

networks:
  rede-monitoramento-hidrico:
    driver: bridge

volumes:
  postgres_data:
  evolution_instances:
