
services:
  # 1. Base de Dados (Persistência para a Evolution API)
  postgres-reservatorio:
    image: postgres:16-alpine
    container_name: postgres-reservatorio
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin_monitor}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${EVOLUTION_DB_NAME:-evolution_db}
    ports:
      - "11432:5432" # Porta externa 11432 para evitar conflitos no Windows
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rede-monitoramento-hidrico

  # 2. Redis (Cache de Performance)
  redis-reservatorio:
    image: redis:7-alpine
    container_name: redis-reservatorio
    restart: unless-stopped
    networks:
      - rede-monitoramento-hidrico

  # 3. Evolution API v2.3.7 (Interface WhatsApp)
  evolution-reservatorio:
    image: evoapicloud/evolution-api:v2.3.7
    container_name: evolution-reservatorio
    restart: unless-stopped
    ports:
      - "11011:8080" # Acesso externo via http://localhost:11011
    environment:
      - SERVER_URL=http://evolution-reservatorio:8080
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=${EVOLUTION_API_KEY}
      
      # Conexão Interna: Sempre usa a porta 5432 do container
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://${POSTGRES_USER:-admin_monitor}:${POSTGRES_PASSWORD}@postgres-reservatorio:5432/${EVOLUTION_DB_NAME:-evolution_db}?schema=public
      - DATABASE_CONNECTION_CLIENT_NAME=monitor_hidrico_v2
      
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis-reservatorio:6379/0
      - CACHE_LOCAL_ENABLED=false
      
      - CONFIG_SESSION_PHONE_WATCH=true
      - QRCODE_LIMIT=30
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - rede-monitoramento-hidrico
    depends_on:
      - postgres-reservatorio
      - redis-reservatorio

  # 4. Bot de Monitoramento (Lógica Distribuída em C)
  bot-monitor:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: bot-monitor-hidrico
    restart: unless-stopped
    environment:
      # URL Oficial do LSDI/UFMA com o seu UUID registrado
      - MIDDLEWARE_URL=${MIDDLEWARE_URL}
      #https://cidadesinteligentes.lsdi.ufma.br/interscity_lh/collector/resources/f0877867-005f-407f-810b-560cd726d5a2/data/last
      
      # Comunicação Interna Docker: Mantemos a porta 8080
      - EVOLUTION_URL=http://evolution-reservatorio:8080
      - INSTANCE_NAME=reservatorio-slz
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - INSTANCE_NAME=${INSTANCE_NAME:-reservatorio-slz}
      
      # Regras de Negócio e Notificação
      - NIVEL_CRITICO=15 
      - GESTOR_JID=${GESTOR_JID}
    networks:
      - rede-monitoramento-hidrico
    depends_on:
      - evolution-reservatorio # Removida a condição 'healthy' para evitar o travamento

networks:
  rede-monitoramento-hidrico:
    driver: bridge

volumes:
  postgres_data:
  evolution_instances: